### ISSUE TITLE
cannot run the codes

### ISSUE THREAD

**Issue by jiaminding** [sarahtattersall/PIPE#101]
I am a green hand to this program. And I try to use "mvn clean compile" to build the codes, it shows "build success", but when I try to use "mvn clean test", it shows that  "/C:/Users/lenovo/Desktop/PIPE/pipe-gui/src/test/java/pipe/actions/type/ImmediateTransitionActionTest.java:[65,24] 不兼容的类型: java.lang.Object无法转换为uk.ac.imperial.pipe.models.petrinet.Transition" , it means "Object cannot transfer to Transition in ImmediateTransitionActionTest.java". I want to ask am i right? Can you help me with this and teach me how to run it?

**Comment by sjdayday** [comment]
Hi,

Would you please include the stacktrace?  Is this the only test that
fails?  What level of Java are you running?  Please run mvn with the -X
flag, and include the output.

Thanks.

Steve

On Sun, Jan 17, 2016 at 6:39 PM, jiaminding <notifications@github.com>
wrote:

> I am a green hand to this program And I try to use "mvn clean compile" to
> build the codes, it shows "build success", but when I try to use "mvn clean
> test", it shows that
> "/C:/Users/lenovo/Desktop/PIPE/pipe-gui/src/test/java/pipe/actions/type/ImmediateTransitionActionTestjava:[65,24]
> 不兼容的类型: javalangObject无法转换为ukacimperialpipemodelspetrinetTransition" , it
> means "Object cannot transfer to Transition in
> ImmediateTransitionActionTestjava" I want to ask am i right? Can you help
> me with this and teach me how to run it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sarahtattersall/PIPE/issues/101>.
>



-- 
Steve Doubleday
UC Irvine
Mathematical Behavioral Sciences
stevedoubleday@gmail.com
818-648-8381

**Comment by jiaminding** [comment]
My level is 5.0.2. And I tried to use "mvn clean test -X" and the problem is still exist.Here is the information.


"[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.
0:testCompile (default-testCompile) on project PIPE-gui: Compilation failure: Co
mpilation failure:
[ERROR] /C:/Users/lenovo/Desktop/PIPE/pipe-gui/src/test/java/pipe/actions/type/I
mmediateTransitionActionTest.java:[65,24] 不兼容的类型: java.lang.Object无法转换
为uk.ac.imperial.pipe.models.petrinet.Transition
[ERROR] /C:/Users/lenovo/Desktop/PIPE/pipe-gui/src/test/java/pipe/actions/type/T
imedTransactionActionTest.java:[66,24] 不兼容的类型: java.lang.Object无法转换为u
k.ac.imperial.pipe.models.petrinet.Transition
[ERROR] -> [Help 1]"

**Comment by sjdayday** [comment]
From within your PIPE directory, please run:

mvn -X install

If there are errors, please send the complete output.
If it completes with no errors, try to run the GUI:

mvn exec:exec -pl pipe-gui

Please note, Java version 7 is required (neither Java 6 nor Java 8 works).

best,
Steve

On Sun, Jan 17, 2016 at 8:37 PM, jiaminding <notifications@github.com>
wrote:

> My level is 5.0.2. And I tried to use "mvn clean test -X" and the problem
> is still exist.Here is the information.
>
> "[ERROR] Failed to execute goal
> org.apache.maven.plugins:maven-compiler-plugin:3.
> 0:testCompile (default-testCompile) on project PIPE-gui: Compilation
> failure: Co
> mpilation failure:
> [ERROR]
> /C:/Users/lenovo/Desktop/PIPE/pipe-gui/src/test/java/pipe/actions/type/I
> mmediateTransitionActionTest.java:[65,24] 不兼容的类型: java.lang.Object无法转换
> 为uk.ac.imperial.pipe.models.petrinet.Transition
> [ERROR]
> /C:/Users/lenovo/Desktop/PIPE/pipe-gui/src/test/java/pipe/actions/type/T
> imedTransactionActionTest.java:[66,24] 不兼容的类型: java.lang.Object无法转换为u
> k.ac.imperial.pipe.models.petrinet.Transition
> [ERROR] -> [Help 1]"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sarahtattersall/PIPE/issues/101#issuecomment-172423156>
> .
>



-- 
Steve Doubleday
UC Irvine
Mathematical Behavioral Sciences
stevedoubleday@gmail.com
818-648-8381

**Comment by sjdayday** [comment]
This is a problem with Java 1.8 compatibility, and is fixed in [PIPE release 5.0.2](https://github.com/sarahtattersall/PIPE/releases/tag/PIPE-5.0.2).
