### ISSUE TITLE
How can i add a property to the transition?

### ISSUE THREAD

**Issue by wumangxing1990** [sarahtattersall/PIPE#103]
which file to change?

**Comment by sjdayday** [comment]
What problem are you trying to solve?  Can you give an example of what a
property would be, and what you would do with the property?

Steve

On Fri, Feb 19, 2016 at 4:23 AM, lizzy <notifications@github.com> wrote:

> which file to change?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sarahtattersall/PIPE/issues/103>.
>



-- 
Steve Doubleday
UC Irvine
Mathematical Behavioral Sciences
stevedoubleday@gmail.com
818-648-8381

**Comment by wumangxing1990** [comment]
I want to use the Petri net to represent Business Process model. By adding a probability property ,i can calculate the similarity between two models.

**Comment by sjdayday** [comment]
I don't know the Petri net literature, but I'm guessing others have worked
on the problem of assessing the similarity between two Petri nets, without
having to add parameters.

An example of how you think this might work, would help me understand.

There is an alpha extension to PIPECore that supports interfaces to
external systems, and some aspects of parameter passing.  Perhaps this
would help you do what you envision.  The code is here:
https://github.com/sarahtattersall/PIPECore/tree/hierarchical-nets
documentation:  https://github.com/sjdayday/PIPECore/wiki

There is no GUI for the new functions however.  You'd have to go through
the unit tests to understand the details, probably starting with
PetriNetRunnerTest.

Steve

On Fri, Feb 19, 2016 at 8:09 PM, lizzy <notifications@github.com> wrote:

> I want to use the Petri net to represent Business Process model. By adding
> a probability property ,i can calculate the similarity between two models.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sarahtattersall/PIPE/issues/103#issuecomment-186502496>
> .
>



-- 
Steve Doubleday
UC Irvine
Mathematical Behavioral Sciences
stevedoubleday@gmail.com
818-648-8381

**Comment by jafarinejad** [comment]
Hello,
how can I show a new module in pipe?
I write an analysis module that implements Imodule interface.  but I do't know haw I can say to gui that it is a module to show it in module tree

**Comment by sjdayday** [comment]
I'm closing this; please re-open if you still have questions.
