### ISSUE TITLE
PIPE 4.3.2 launch fails (Win 8.1 64-bit)

### ISSUE THREAD

**Issue by DrEti** [sarahtattersall/PIPE#104]
Hi,

Just an end-user, posting here as recommended on the project's Sourceforge page.
As I try to launch PIPE 4.3.2 via batch file (from the directory 'as extracted'), the following Error is generated: "Could not find or load main class Pipe".
Just double checking whether it's just something silly I'm missing here, or it's the symptom of some known compatibility issue etc.

Thank you in advance

Regards,
Ettore

**Comment by sjdayday** [comment]
Hi Ettore,

So you ran launch.bat, and got that error?  Would you send a listing of the
directory you were in when you got the error, as well as the "Pipe"
directory and the "Pipe/lib" directory?

You may want to check out the new version of Pipe at some point (
https://github.com/sarahtattersall/PIPE), but right now it has a bug and
doesn't run on Windows.

Thanks.

Steve

On Mon, Mar 7, 2016 at 9:55 AM, DrEti <notifications@github.com> wrote:

> Hi,
>
> Just an end-user, posting here as recommended on the project's Sourceforge
> page.
> As I try to launch PIPE 4.3.2 via batch file (from the directory 'as
> extracted'), the following Error is generated: "Could not find or load main
> class Pipe".
> Just double checking whether it's just something silly I'm missing here,
> or it's the symptom of some known compatibility issue etc.
>
> Thank you in advance
>
> Regards,
> Ettore
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sarahtattersall/PIPE/issues/104>.
>



-- 
Steve Doubleday
UC Irvine
Mathematical Behavioral Sciences
stevedoubleday@gmail.com
818-648-8381

**Comment by DrEti** [comment]
Hi Steve,

Thank you for your prompt reply

Please find attached a snapshot taken from the command window - the
directory path should be visible.
Re what's in the PIPE directory - it's just the content 'as unzipped' from
the compressed file downloadable from Sourceforge.

Please let me know if this helps

Regards,
Ettore



2016-03-07 20:16 GMT+00:00 Steve Doubleday <notifications@github.com>:

> Hi Ettore,
>
> So you ran launch.bat, and got that error? Would you send a listing of the
> directory you were in when you got the error, as well as the "Pipe"
> directory and the "Pipe/lib" directory?
>
> You may want to check out the new version of Pipe at some point (
> https://github.com/sarahtattersall/PIPE), but right now it has a bug and
> doesn't run on Windows.
>
> Thanks.
>
> Steve
>

**Comment by sjdayday** [comment]
Hi Ettore -- the screenshot didn't come through.  Please send it me
directly:  stevedoubleday [at] gmail.com.  Thanks.  Steve

On Tue, Mar 8, 2016 at 12:55 AM, DrEti <notifications@github.com> wrote:

> Hi Steve,
>
> Thank you for your prompt reply
>
> Please find attached a snapshot taken from the command window - the
> directory path should be visible.
> Re what's in the PIPE directory - it's just the content 'as unzipped' from
> the compressed file downloadable from Sourceforge.
>
> Please let me know if this helps
>
> Regards,
> Ettore
>
>
>
> 2016-03-07 20:16 GMT+00:00 Steve Doubleday <notifications@github.com>:
>
> > Hi Ettore,
> >
> > So you ran launch.bat, and got that error? Would you send a listing of
> the
> > directory you were in when you got the error, as well as the "Pipe"
> > directory and the "Pipe/lib" directory?
> >
> > You may want to check out the new version of Pipe at some point (
> > https://github.com/sarahtattersall/PIPE), but right now it has a bug and
> > doesn't run on Windows.
> >
> > Thanks.
> >
> > Steve
> >
> > On Mon, Mar 7, 2016 at 9:55 AM, DrEti <notifications@github.com> wrote:
> >
> > > Hi,
> > >
> > > Just an end-user, posting here as recommended on the project's
> > Sourceforge
> > > page.
> > > As I try to launch PIPE 4.3.2 via batch file (from the directory 'as
> > > extracted'), the following Error is generated: "Could not find or load
> > main
> > > class Pipe".
> > > Just double checking whether it's just something silly I'm missing
> here,
> > > or it's the symptom of some known compatibility issue etc.
> > >
> > > Thank you in advance
> > >
> > > Regards,
> > > Ettore
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/sarahtattersall/PIPE/issues/104>.
> > >
> >
> >
> >
> > --
> > Steve Doubleday
> > UC Irvine
> > Mathematical Behavioral Sciences
> > stevedoubleday@gmail.com
> > 818-648-8381
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/sarahtattersall/PIPE/issues/104#issuecomment-193431415>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sarahtattersall/PIPE/issues/104#issuecomment-193669225>
> .
>



-- 
Steve Doubleday
UC Irvine
Mathematical Behavioral Sciences
stevedoubleday@gmail.com
818-648-8381

**Comment by sjdayday** [comment]
Continued through offline email.  I believe this is resolved.  Please re-open if I'm wrong.  

As of today, PIPE now runs under Windows, using [release 5.0.2](https://github.com/sarahtattersall/PIPE/releases/tag/PIPE-5.0.2)
