### ISSUE TITLE
cant build, packages missing!

### ISSUE THREAD

**Issue by nise** [sarahtattersall/PIPE#13]
There seem to be some private packages necessary that are not delivered as Open Source. I am not a big friend of java programming. If you could provide me a binary i would be happy.

[ERROR] Failed to execute goal on project PIPE: Could not resolve dependencies for project uk.ac.imperial:PIPE:jar:4.3.1: The following artifacts could not be resolved: uk.ac.imperial:tools:jar:1.0, uk.ac.imperial:hadoop-dev-core:jar:0.13.1, uk.ac.imperial:drmaa:jar:1.0, uk.ac.imperial:jama:jar:1.0.2, uk.ac.imperial:powerswing:jar:0.3, uk.ac.imperial:jpowergraph-swing:jar:0.2, uk.ac.imperial:jpowergraph-common:jar:0.2: Could not find artifact uk.ac.imperial:tools:jar:1.0 in central (http://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]

**Comment by henrytirla** [comment]
I am currently having the same issue and using going through the readme file isn't of much help
