### ISSUE TITLE
GSPN Analysis module returning 'I/O Error' and not able to use Steady State Analysis Module

### ISSUE THREAD

**Issue by femodguru** [sarahtattersall/PIPE#16]
Hello:
Can you help in investigating the following error messages encountered using PIPE2 on my project.
1.  GSPN analysis module returning 'I/O Error'.
2. I get the following error msg 'Unable to connect to server camelot01.doc.ic.ac.uk : 55500: Connection refused: connect'. Can you advise on how to get access to the 'camelot' server that the steady state analysis module connects to? 
   Thanks

**Comment by jafarinejad** [comment]
Hi,
I want to use pipe for passage time analysis from one state to another.
I use pie 3, pipe 4. but I can't get analysis. for example dnamaca in pipe 3 results " Unable to connect to server camelot01.doc.ic.ac.uk : 55500: Connection timed out: connect".
and in pipe 4, 4.2, 4.3 it remains in opening connection for performance query editor.
would any body help me about the issue?

**Comment by sjdayday** [comment]
I'm not familiar with the performance analysis, and won't be spending time on it in the future.  

I think the research on which this was based is [here](http://www.doc.ic.ac.uk/~wjk/publications/brien-dingle-knottenbelt-kulatunga-suto-pdmc-2008.pdf), which may help you decide if this is what you need.  However, as stated earlier, this approach may not be supported.   

Steve

**Comment by jafarinejad** [comment]
thank you for your answer. I model the net example of the file. but, it can't connect to server..
i don't find executable file of pipe 5. I just find its source file and I have problem in running it in eclipse. (failure for some of libs of ac.imperial) can you help me about running it or send its site of executable file?
i want to test performance analysis of it. perhaps it connect and run my query. thanks

**Comment by sjdayday** [comment]
Unfortunately, PIPE V5 has little support yet for analysis modules.  The
performance analysis module is not yet supported.  If you would still like
to run V5, I'm happy to help -- please start here:
https://github.com/sarahtattersall/PIPE.  The most current release is here:
 https://github.com/sarahtattersall/PIPE/releases

best,
Steve

On Wed, Jun 29, 2016 at 10:12 PM, jafarinejad <notifications@github.com>
wrote:

> thank you for your answer. I model the net example of the file. but, it
> can't connect to server..
> i don't find executable file of pipe 5. I just find its source file and I
> have problem in running it in eclipse. (failure for some of libs of
> ac.imperial) can you help me about running it or send its site of
> executable file?
> i want to test performance analysis of it. perhaps it connect and run my
> query. thanks
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/sarahtattersall/PIPE/issues/16#issuecomment-229561006>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACAHxiaccOVpHKOyFkTPGOyhmiJ5LUlxks5qQ1A4gaJpZM4BUSam>
> .
>



-- 
Steve Doubleday
PhD candidate, Mathematical Behavioral Sciences
UC Irvine
stevedoubleday@gmail.com
818-648-8381
