### ISSUE TITLE
weight expression editor immediately pops down

### ISSUE THREAD

**Issue by hlindberg** [sarahtattersall/PIPE#88]
When clicking on the Arc Weight Expression Editor's button marked "Weight expression editor" I expect an editor to appear. 

What happens is that an editor shows momentarily only to disappear again. This editor appears in the upper left hand of the screen. Repeated clicking has the same effect. Changing the weight value to some other number than 1 has no effect on the behavior of the disappearing editor (the number takes effect when closing with ok).

**Comment by sjdayday** [comment]
Hi Henrik,

I also see what you are seeing.  Let me take a look at what's going on.

best,
Steve

On Tue, Jun 23, 2015 at 6:15 PM, Henrik Lindberg <notifications@github.com>
wrote:

> When clicking on the Arc Weight Expression Editor's button marked "Weight
> expression editor" I expect an editor to appear.
>
> What happens is that an editor shows momentarily only to disappear again.
> This editor appears in the upper left hand of the screen. Repeated clicking
> has the same effect. Changing the weight value to some other number than 1
> has no effect on the behavior of the disappearing editor (the number takes
> effect when closing with ok).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sarahtattersall/PIPE/issues/88>.
>



-- 
Steve Doubleday
UC Irvine
Mathematical Behavioral Sciences
stevedoubleday@gmail.com
818-648-8381

**Comment by sjdayday** [comment]
Hi Henrik,

It turns out this was fixed previously, but is not in the current released "uber jar" (PIPE-gui-5.0.0.jar).  If you clone the repository and build it manually following the readme instructions, you should be able to run PIPE and see the weight expression editor.   If you have problems with that, let me know and I'll package a bug release.  

best,
Steve
