### ISSUE TITLE
is there support for colored tokens?

### ISSUE THREAD

**Issue by hlindberg** [sarahtattersall/PIPE#89]
There is a drop down labeled "Default" that only contains "Default" as a choice. When clicking on "configure tokens", it is mentioned again, and there is a selection of colors.

Is this just for decoration or can I add tokens of different colors and use them in expressions?

In particular I want to model a transition that if there are blue tokens in two places, a transition selects those (but no other colors).

**Comment by sjdayday** [comment]
Hi Henrik,

Yes, you may add tokens of different colors and use them in expressions.
Give it a try and let us know if you have problems.

best,
Steve Doubleday

On Tue, Jun 23, 2015 at 6:17 PM, Henrik Lindberg <notifications@github.com>
wrote:

> There is a drop down labeled "Default" that only contains "Default" as a
> choice. When clicking on "configure tokens", it is mentioned again, and
> there is a selection of colors.
>
> Is this just for decoration or can I add tokens of different colors and
> use them in expressions?
>
> In particular I want to model a transition that if there are blue tokens
> in two places, a transition selects those (but no other colors).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sarahtattersall/PIPE/issues/89>.
>



-- 
Steve Doubleday
UC Irvine
Mathematical Behavioral Sciences
stevedoubleday@gmail.com
818-648-8381

**Comment by hlindberg** [comment]
I am not able to figure out how to add a token of a particular color. How do I add one?

**Comment by sjdayday** [comment]
Hi Henrik,

Looks like there is a bug in the token editor.  I'm working on it.  Thanks
for pointing it out.

regards,
Steve

On Wed, Jun 24, 2015 at 5:31 AM, Henrik Lindberg <notifications@github.com>
wrote:

> I am not able to figure out how to add a token of a particular color. How
> do I add one?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sarahtattersall/PIPE/issues/89#issuecomment-114850517>
> .
>



-- 
Steve Doubleday
UC Irvine
Mathematical Behavioral Sciences
stevedoubleday@gmail.com
818-648-8381

**Comment by sjdayday** [comment]
Hi Henrik,

I should have this bug and the bug in the weight expression editor fixed
Friday (I'm in GMT -7), and an updated version of PIPE available.  Thanks
for pointing these out.

regards,
Steve

On Wed, Jun 24, 2015 at 10:35 AM, Steve Doubleday <stevedoubleday@gmail.com>
wrote:

> Hi Henrik,
>
> Looks like there is a bug in the token editor.  I'm working on it.  Thanks
> for pointing it out.
>
> regards,
> Steve
>
> On Wed, Jun 24, 2015 at 5:31 AM, Henrik Lindberg <notifications@github.com
> > wrote:
>
>> I am not able to figure out how to add a token of a particular color. How
>> do I add one?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/sarahtattersall/PIPE/issues/89#issuecomment-114850517>
>> .
>>
>
>
>
> --
> Steve Doubleday
> UC Irvine
> Mathematical Behavioral Sciences
> stevedoubleday@gmail.com
> 818-648-8381
>



-- 
Steve Doubleday
UC Irvine
Mathematical Behavioral Sciences
stevedoubleday@gmail.com
818-648-8381

**Comment by sjdayday** [comment]
Hi Henrik
I had forgotten how the token editor works; it's not very intuitive.  Once you enter a label for a given token color, e.g., "red", then tab out of the field.  That causes the update.    
![token editor](https://cloud.githubusercontent.com/assets/2099142/8387573/918c9784-1c0e-11e5-9b4f-c94cc944c1aa.png)
In the example above, I hadn't tabbed out of the "blue" field before I hit ok, so the only token that was  saved is "red":
![token dropdown](https://cloud.githubusercontent.com/assets/2099142/8387643/2357d868-1c0f-11e5-8b8b-ab21901e5f08.png)

To see an example of a colored net:  File / Open .... pipe-gui/src/main/resources/extras/examples/Accident & Emergency Unit Coloured.xml

Hope that helps.

best,
Steve
