### ISSUE TITLE
Export doesn't work

### ISSUE THREAD

**Issue by nono313** [sarahtattersall/PIPE#94]
I have tried the three export options but not one of them seem to do anything.
Is that expected ?

**Comment by sjdayday** [comment]
Yes, unfortunately.  I've updated messages for two of them in [PIPE release 5.0.2](https://github.com/sarahtattersall/PIPE/releases/tag/PIPE-5.0.2) to at least tell the user that it doesn't work.  I'll be working on other areas in the next few months, and don't know if / when I'd get to this.
