### ISSUE TITLE
Where can i find the documents for developers?

### ISSUE THREAD

**Issue by wumangxing1990** [sarahtattersall/PIPE#99]
Where can i find the documents for developers of PIPE?

**Comment by sjdayday** [comment]
Hi,

The best documentation is the unit tests (https://github.com/sarahtattersall/PIPECore/tree/master/src/test/java/uk/ac/imperial/pipe), which show the details of how the functionality in PIPECore is used.   Sarah's thesis gives good general background of how the old PIPE V4 was refactored:  http://www.doc.ic.ac.uk/teaching/distinguished-projects/2014/s.tattersall%20.pdf

For the extensions to support external interfaces and hierarchical nets, again the unit tests are the detailed documentation, but the high-level design is here:  https://github.com/sjdayday/PIPECore/wiki.

Hope that helps.

Steve

**Comment by wumangxing1990** [comment]
thanks
